FROM ubuntu:18.04

MAINTAINER Iain Mackie

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    wget vim \
    software-properties-common \
    locales
    
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en

RUN add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get install -y python3 \
    python3-pip \
    python-setuptools

RUN pip3 install --force-reinstall --upgrade pip
RUN pip install tensorflow==2.0.0-rc1 tensorflow_datasets
RUN pip install torch torchvision
# RUN pip install jupyter jupyterlab tokenizer
RUN pip install torchtext pytorch-nlp nltk line_profiler runipy dotmap
RUN pip install cbor
RUN pip install transformers

#RUN apt-get install -y curl nodejs npm
#RUN jupyter labextension install jupyterlab-drawio
#RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager

# RUN git config --global user.email "aquaktus@yahoo.co.uk"
# RUN git config --global user.name "aquaktus"

CMD echo "STARTED POD"
CMD python3 /nfs/trec_car/data/bert_reranker_datasets/bert-reranker/trec_car_preprocessing.py

